"""add chat_id to chat_messages with nullable=True

Revision ID: 57778b8a9da8
Revises: 19af67e3348c
Create Date: 2026-04-19 15:32:07.788397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57778b8a9da8'
down_revision: Union[str, None] = '19af67e3348c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
